
import java.awt.Frame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author matheus
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
     
        
        initComponents();
    
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechar = new javax.swing.JButton();
        inutil = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        ComboBox1 = new javax.swing.JComboBox<>();
        tf1 = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        ComboBox2 = new javax.swing.JComboBox<>();
        tf2 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de temperaratura");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(27, 35, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icone(mini).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conversor de temperarturas");

        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fechar.png"))); // NOI18N
        fechar.setBorderPainted(false);
        fechar.setContentAreaFilled(false);
        fechar.setFocusPainted(false);
        fechar.setMaximumSize(new java.awt.Dimension(10, 10));
        fechar.setMinimumSize(new java.awt.Dimension(10, 10));
        fechar.setPreferredSize(new java.awt.Dimension(10, 10));
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        inutil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btninutil.png"))); // NOI18N
        inutil.setBorderPainted(false);
        inutil.setContentAreaFilled(false);
        inutil.setFocusPainted(false);
        inutil.setMaximumSize(new java.awt.Dimension(10, 10));
        inutil.setMinimumSize(new java.awt.Dimension(10, 10));
        inutil.setPreferredSize(new java.awt.Dimension(10, 10));

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MINIZAR.png"))); // NOI18N
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setFocusPainted(false);
        minimizar.setMaximumSize(new java.awt.Dimension(10, 10));
        minimizar.setMinimumSize(new java.awt.Dimension(10, 10));
        minimizar.setPreferredSize(new java.awt.Dimension(10, 10));
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });

        ComboBox1.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin", "" }));

        tf1.setBackground(new java.awt.Color(46, 55, 75));
        tf1.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 255, 255));
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf1.setBorder(null);

        calcular.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        calcular.setForeground(new java.awt.Color(0, 0, 0));
        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn.png"))); // NOI18N
        calcular.setText("CALCULAR");
        calcular.setBorderPainted(false);
        calcular.setContentAreaFilled(false);
        calcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        apagar.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        apagar.setForeground(new java.awt.Color(0, 0, 0));
        apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn.png"))); // NOI18N
        apagar.setText("Apagar");
        apagar.setBorderPainted(false);
        apagar.setContentAreaFilled(false);
        apagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        ComboBox2.setFont(new java.awt.Font("Leelawadee UI", 1, 15)); // NOI18N
        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin", "" }));

        tf2.setBackground(new java.awt.Color(46, 55, 75));
        tf2.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        tf2.setForeground(new java.awt.Color(255, 255, 255));
        tf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf2.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inutil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(tf2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inutil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBox1)
                    .addComponent(tf1)
                    .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBox2)
                    .addComponent(tf2)
                    .addComponent(apagar))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
      
        this.setState(Frame.ICONIFIED);
        
    }//GEN-LAST:event_minimizarActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
       
        tf1.setText("");
        tf2.setText("");
        
    }//GEN-LAST:event_apagarActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_fecharActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       
         
       String box1 = (String)ComboBox1.getSelectedItem();
       String box2 = (String)ComboBox2.getSelectedItem();
       
       if (box1.equals("Celsius") && box2.equals("Fahrenheit")){
           
           double c = Double.parseDouble(tf1.getText());
           
           double f = (double)(c * 1.8 + 32);
           
           String r = String.format("%.0f",f);
           
           tf2.setText(r);
           
       } else{
           
           if (box1.equals("Celsius") && box2.equals("Kelvin")){
               
               double c = Double.parseDouble(tf1.getText());
               
               double k = (double)(c + 273.15);
               
               String r = String.format("%.2f",k);
           
               tf2.setText(r);
               
           }
            
       }
       
       //-------------------------------------------------------------------------------------------------/
       
       if (box1.equals("Fahrenheit") && box2.equals("Kelvin")){
               
               Double f = Double.parseDouble(tf1.getText());
               
               Double k = ((f - 32)* 5/9 + 273.15);
               
               String r = String.format("%.3f",k);
               
               tf2.setText(r);
               
           } else {
               
               if (box1.equals("Fahrenheit") && box2.equals("Celsius")){
                   
                   Double f = Double.parseDouble(tf1.getText());
                   
                   Double c = ((f - 32) * 5/9);
                   
                   String r = String.format("%.2f", c);
                   
                   tf2.setText(r);
                   
               }
               
             }
           
       
       //-------------------------------------------------------------------------------------------------/
       
       if (box1.equals("Kelvin") && box2.equals("Celsius")){
           
           Double k = Double.parseDouble(tf1.getText());
           
           Double c = k -  273.15;
           
           String r = String.format("%.2f", c);
           
           tf2.setText(r);
           
       } else {
           
           if (box1.equals("Kelvin") && box2.equals("Fahrenheit")){
               
                Double k = Double.parseDouble(tf1.getText());
                
                Double f = (k - 273.15) * 9/5 + 32;
                
                String r = String.format("%.2f", f);
                
                tf2.setText(r);
                
           }
           
       }
       
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JButton apagar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton fechar;
    private javax.swing.JButton inutil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizar;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
